// Tracked copy of the image-module declarations that next-env.d.ts (gitignored,
// generated by `next build`) provides, so `npm run typecheck` also passes on a
// fresh checkout before any build (e.g. the article pipeline gate in CI).
/// <reference types="next/image-types/global" />
